spring:
  application:
    name: service-order
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: false
    instance-id: http://${eureka.instance.hostname}:${server.port}
    ip-address: ${eureka.instance.hostname}
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  retryable: true
  MaxAutoRetries: 1
